version: '3.8'

services:
  eureka-server:
    image: eurekaserver:latest
    build:
      context: ./eurekaserver
    ports:
      - "8761:8761"
    networks:
      - spring-net

  api-gateway:
    image: apigateway:latest
    build:
      context: ./apigateway
    ports:
      - "8080:8080"
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-server:8761/eureka/
    networks:
      - spring-net
    depends_on:
      - eureka-server

  userservice:
    image: userservice:latest
    build:
      context: ./userservice
    ports:
      - "8081:8081"
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-server:8761/eureka/
    networks:
      - spring-net
    depends_on:
      - eureka-server

networks:
  spring-net:
    driver: bridge
